### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#1]
Здесь будет логотип, а не заголовок 1-го уровня
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L12

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Читай пункт 3.10 ТЗ...

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Правда???
https://github.com/ShindekiSan/Device/blob/46329d5d4ce63b84e63962dd1e38ae63a6470c05/catalog.html#L119

**Comment by ShindekiSan** [comment]
Исправил
