### ISSUE TITLE
Несоответствие ТЗ

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#10]
Твой код
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L60-L84

не соответствует пункту 3.5 Технического задания. Вот выдержка из задания:
"3.5. Блоки с названиями разделов («виртуальная реальность», «моноподы для
селфи», ...) являются ссылками на разделы каталога."

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Ну как бы да... Вот только вопрос: где-то прописано требование, чтобы ссылки открывались в новой вкладке?
https://github.com/ShindekiSan/Device/blob/3e9566660bc4b5ddba5b84c9e7aa84a9adbbfdf7/index.html#L59

**Comment by ShindekiSan** [comment]
Исправил
