### ISSUE TITLE
Навигация

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#11]
1. Любопытно, почему каталог товаров не попал в навигацию?
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L22-L31
2. Что-то мне подсказывает, что ссылка на авторизацию, а также сравнение и корзина не относятся к навигации по сайту
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L14-L20

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
А 2-й пункт замечания?
А страница каталога?
https://github.com/ShindekiSan/Device/blob/3e9566660bc4b5ddba5b84c9e7aa84a9adbbfdf7/catalog.html#L10-L33

**Comment by ShindekiSan** [comment]
Исправил
