### ISSUE TITLE
Несоответствие макету

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#13]
Макет: http://joxi.ru/LmG1PXeIJ8kzaA
Код:
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/catalog.html#L79
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/catalog.html#L86
ну и далее по коду ...

**Comment by ShindekiSan** [comment]
Исправил
