### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#14]
Необходимо решить вопрос с Warning!
http://joxi.ru/gmv4yJvTv3yW6A
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L210-L229

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
https://gyazo.com/dda4b51afdb42b7624464ac94e290d9c
https://gyazo.com/a04af70ad8311c4038c58349cf4db138

При валидации ошибок быть не должно, от слова "совсем"!

**Comment by ShindekiSan** [comment]
переделал
