### ISSUE TITLE
Заголовки

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#15]
Это вообще не заголовки, ну вот ни разу!
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L48

Здесь H2
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L40

Здесь H3
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L48
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L101

**Comment by ShindekiSan** [comment]
переделал
