### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#16]
Не вижу на этой странице разметку блока авторизации:
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L18-L25
А здесь, наоборот, отсутствует блок авторизованного пользователя:
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L18-L24

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Неправильно...
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L23-L25
1. Класс visually-hidden "вешаем" только на те вещи, которые никогда не показываются на странице, вообще ни разу, но в разметке быть должны. Следовательно - в данном коде этого класса быть не должно!
2. Следует отделить блок авторизованного пользователя от кода авторизации (можно обернуть дивом)

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Вот как чувствовал, что в футере ты не посмотришь...
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/catalog.html#L204-L206

**Comment by ShindekiSan** [comment]
Исправил
