### ISSUE TITLE
Поиск по сайту

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#17]
Поиск по сайту - это не просто поле ввода! Здесь должна быть форма!!!
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L15

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
ну и что это такое? не помнишь, как submit прописывается?
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/catalog.html#L19

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Нет, не переделал!
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/index.html#L19
А вообще - я уже устал одну и ту же проблему указывать вначале на одной странице, а затем отдельно на второй. Если есть ошибка - тебе надо весь код пересмотреть самостоятельно на предмет подобных ошибок, иначе ты так ничему и не научишься

**Comment by ShindekiSan** [comment]
Исправил. Буду тщательнее код пересматривать
