### ISSUE TITLE
Критерий Б15

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#18]
Нарушение критерия Б15
http://joxi.ru/KAx48GoT1gnzgA
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L27-L42

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Подскажи, мне нужно каждый фрагмент кода тебе специально выделить?
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L149-L153

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Больше на этот критерий указывать не буду до финальной проверки (если дойдём)
http://joxi.ru/EA4Py7zTOBd7wA
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/index.html#L37-L44

**Comment by ShindekiSan** [comment]
буду впредь пересматривать вместо 2-ух раз 3 или 4. Исправил

**Comment by Morfey216** [comment]
Критерий требует исполнения не только в верстке...
https://github.com/ShindekiSan/Device/blob/2e699c7bc2909553651e447d1722e8d3b629af1c/css/style.css#L222-L233

http://joxi.ru/4Ak4KBoTXp84Nr

**Comment by ShindekiSan** [comment]
исправил
