### ISSUE TITLE
Форматирование кода

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#19]
Такой текст в разметке можно писать в одну строку
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L52-L54

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L162-L165

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Не исправлено!
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/index.html#L157-L160

**Comment by ShindekiSan** [comment]
исправил
