### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#2]
Здесь будет ссылка, а не кнопка:
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L23

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Это тоже ссылка:
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/catalog.html#L16

**Comment by ShindekiSan** [comment]
Исправил
