### ISSUE TITLE
Критерий Б1

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#20]
1. Отсутствует разметка слайдов
http://joxi.ru/12MqPGYH0EqVZ2
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L144-L154

2. В каталоге эти элементы также должны быть размечены http://joxi.ru/1A5P7NxTG30932

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L160-L161
Уже писал раньше за эти классы https://github.com/ShindekiSan/Device/issues/16#issuecomment-640129664

Пока просто пропиши слайды, чтобы их было видно. Скроешь на этапе написания стилей

**Comment by ShindekiSan** [comment]
переделал
