### ISSUE TITLE
Форма письма

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#21]
1. Отсутствует атрибут action
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L211
2. Это скорее блок, а не параграф
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L212-L215
3. Неправильное значение type
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L218
4. input не является многострочным полем
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L222
5. Кнопка отправки формы должна быть ВНУТРИ формы
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L225
6. Не вижу в разметке кнопки закрытия модального окна

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Остались ошибки
1.
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L243
Читать здесь: http://htmlbook.ru/html/textarea


2. Это кнопка закрытия модального окна или формы? Что-то мне подсказывает, что она не на своем месте
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L246

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Не знаю, на что ты там "переделал", но ошибка осталась
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/index.html#L234

**Comment by ShindekiSan** [comment]
теперь уж точно переделал.
