### ISSUE TITLE
Значение полей формы

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#23]
Два вопроса:
1. Подскажи, какой цвет выбрал пользователь: `value="1"` ?
2. На какой вопрос пользователь дал положительный ответ? 
`<input type="radio" name="choice" id="choice-yes" value="yes">`

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Не совсем...
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/catalog.html#L101
Здесь нужно правильно прописать name, именно этот атрибут и определяет суть данных, а value сократится до банального да/нет
`<input type="radio" name="choice-bluetooth" id="choice-yes" value="yes">`

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Если хочешь, чтобы радио-баттоны работали правильно, атрибут name в пределах одной группы инпутов должен совпадать
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/catalog.html#L100-L107

**Comment by ShindekiSan** [comment]
исправил
