### ISSUE TITLE
submit

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#24]
Всего одна строка кода https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L98
1. Это КНОПКА, а не ссылка
2. Кнопка отправки должна находиться ВНУТРИ формы, а не за ее пределами

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Это что за порнография?
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/catalog.html#L110
`<button type="submit">Показать</button>` - так правильно! Больше по формам подсказывать не буду - учи матчасть!!!

**Comment by ShindekiSan** [comment]
переделал
