### ISSUE TITLE
Навигация

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#26]
Элементы навигации следует вынести в отдельный блок
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L155-L161

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Разве это навигация по структурным разделам сайта?
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/catalog.html#L173-L181
DOC: https://developer.mozilla.org/ru/docs/Web/HTML/Element/nav

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Ссылки добавил, а вот тег nav остался, в данном случае правильнее будет заменить на div, так как section ты вообще, по сути, не используешь (а зря... хоть это и не ошибка)
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/catalog.html#L173-L181

**Comment by ShindekiSan** [comment]
переделал. А section по логике можно использовать для вынесения каких либо частей сайта(обёртка) вместо дива? Если например говорить о секции сайта с навигацией и подобное.

**Comment by Morfey216** [comment]
Не просто "каких-либо", не все разделы можно помещать в section. 
Тег `<section>` обозначает крупный смысловой (или «логический») раздел. Смысловому разделу обычно можно дать имя, описывающее его содержание, как главы в книге.
Процитирую выдержку из курса:

Небольшая подсказка как отличать смысловые или логические разделы от структурных разделов. Логический раздел вы можете осмысленно назвать одним словом или словосочетанием: «программа обучения», «каталог», «наши преимущества». Если же в голову приходят названия, которые указывают на его положение на странице («шапка», «подвал», «левая колонка»), либо перечисления («новости и галерея», «фильтры и товары»), в таком случае раздел структурный и тег `<section>` для него не подходит.

**Comment by ShindekiSan** [comment]
Благодарю
