### ISSUE TITLE
Метод формы

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#27]
В формах передачи данных рекомендуется использовать метод POST
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/catalog.html#L52

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Я говорил про формы передачи данных... В форме поиска уместен GET
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/catalog.html#L15

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
Неужели???????
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/index.html#L15

**Comment by ShindekiSan** [comment]
не заметил, переделал
