### ISSUE TITLE
Критерий Б4 (грубые ошибки в разметке)

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#28]
Это совсем не кнопки:
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/catalog.html#L122-L123

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/catalog.html#L122-L123
1. Это не Следующая и Предыдущая страница. Данный элемент интерфейса сортирует по возрастанию и убыванию, а не страницы переключает. 
2. Изображения ("треугольнички") добавятся на этапе стилизации или при добавлении графики, т.к. речь идет об svg

**Comment by ShindekiSan** [comment]
переделал
