### ISSUE TITLE
Заголовок H1

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#3]
На странице должен быть только один заголовок 1-го уровня
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L40
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L47
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L51
ну и ниже по коду тоже...

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Серьёзно?
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L40
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L117

**Comment by ShindekiSan** [comment]
Исправил, не заметил его

**Comment by Morfey216** [comment]
> Исправил, не заметил его

На это есть инструмент "Поиск"

А теперь посмотрим твой вариант заголовка:
https://github.com/ShindekiSan/Device/blob/3e9566660bc4b5ddba5b84c9e7aa84a9adbbfdf7/index.html#L38
а что будешь делать в этом случае? http://joxi.ru/a2XRBdZTDzXGdr

Позволю себе повторить то, что писал тебе ранее:

> Что касается макетов вообще и этого в частности - не всегда в макете есть явно видный (в дизайне) заголовок первого уровня. Однако в любом случае в разметку его рекомендуют добавлять, и при необходимости скрывать специальным образом. Пока что для таких элементов можешь добавлять класс .visually-hidden , позже дам стили для него

Другими словами: заголовок 1-го уровня - это самый важный заголовок на странице, он определяет назначение и смысл всей страницы (или даже сайта) сразу и в целом. 
Если в макете дизайнер явным образом не прописал такой заголовок, то его нужно придумать и добавить в верстку в скрытом виде.
Макет Device как раз из таких - в нём нет явно прорисованного заголовка первого уровня

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
Что-то не наблюдаю заголовка H1
https://github.com/ShindekiSan/Device/blob/20a0999be2fde07400edbc88ab79c59daf2e4441/index.html#L46-L50

**Comment by ShindekiSan** [comment]
переделал
