### ISSUE TITLE
Странные параграфы

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#30]
Наверняка в них скрыта очень важная информация
https://github.com/ShindekiSan/Device/blob/f3bed4cf5f10cde37272a4bc73d6cfdef973c17c/index.html#L55

**Comment by ShindekiSan** [comment]
переделал

**Comment by Morfey216** [comment]
А теперь "одинокие спанчики"
https://github.com/ShindekiSan/Device/blob/938ff3d1c72151f36dbd705cd913272dcf8f9630/index.html#L57

В этих фрагментах кода нет НИКАКОЙ ПОЛЕЗНОЙ информации! Следовательно - это декоративные элементы и в разметке их быть не должно!

**Comment by ShindekiSan** [comment]
убрал
