### ISSUE TITLE
Глобальные стили

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#34]
У тебя очень "интересный" способ стилизации...
Один из примеров: https://github.com/ShindekiSan/Device/blob/2e699c7bc2909553651e447d1722e8d3b629af1c/css/style.css#L335

А всё почему? А всё потому, что на этапе вёрстки не продумал логическую структуру документа и не прописал классы.
К чему может привести твой подход, поясню на примере... Я выделил только один заголовок...
1. по твоей верстке ВСЕ (ну, почти все...) заголовки h3 на странице каталога будут иметь такие стили
2. что будет со стилями этого фрагмента, если вдруг (а такое бывает) заказчик изменит уровень заголовка? Или сделает здесь просто `div` или параграф?
http://joxi.ru/Q2KNPJYHwP6Q6m

Короче - глобальной стилизации быть не должно (критерий Д25)

**Comment by ShindekiSan** [comment]
пересмотрел, переделал.
