### ISSUE TITLE
Атрибуты img

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#4]
Для всех контентных изображений необходимо указывать атрибуты width, height и alt
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L36-L38

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
В качестве атрибута alt для карты правильно было бы прописывать адрес компании, а не безликое слово Карта...
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L119

**Comment by ShindekiSan** [comment]
Исправил

**Comment by Morfey216** [comment]
ОК. И последний пока момент: атрибуты размеров изображения прописывают обычно в порядке "ширина" "высота", т.е. например width="300" height="200"
Это вроде как и не ошибка, но так повелось и лучше придерживаться общего принципа

**Comment by ShindekiSan** [comment]
Исправил
