### ISSUE TITLE
Изображения

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#7]
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L99

Если это изображение этого человечка http://joxi.ru/L21PxnzTgpZGDm
то это ошибка... В разметку мы добавляем только смысловые изображения: изображение товаров, логотипы, бренды и т.д., все декоративные вещи - через стили

**Comment by ShindekiSan** [comment]
исправил
