### ISSUE TITLE
Типы ссылок

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#8]
это ссылка:
https://github.com/ShindekiSan/Device/blob/2269246cb45df3a5b5664bca22a7fd8bdea972f1/index.html#L146
смотреть здесь (в Примерах есть правильность написания): https://developer.mozilla.org/ru/docs/Web/HTML/Element/a

**Comment by ShindekiSan** [comment]
исправил

**Comment by Morfey216** [comment]
Не исправлено! Я ссылку на материал дал не просто так, в примерах описано, как именно оформляются ссылки на телефон и почту
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L148

**Comment by ShindekiSan** [comment]
Теперь точно исправлено
