### ISSUE TITLE
Отсутствует разметка элементов

### ISSUE THREAD

**Issue by Morfey216** [ShindekiSan/Device#9]
Социалки тоже должны быть в разметке
http://joxi.ru/nAy4NExTjBvXd2

и ссылка на академию тоже... http://joxi.ru/1A5P7NxTG5ODz2

**Comment by ShindekiSan** [comment]
исправил

**Comment by Morfey216** [comment]
Любопытно - почему с маленькой буквы?
https://github.com/ShindekiSan/Device/blob/c438cee14a1448b493c58abb2bb52f11624f7f37/index.html#L137-L139

**Comment by ShindekiSan** [comment]
Исправил, буду знать на будущее

**Comment by Morfey216** [comment]
> Исправил, буду знать на будущее

Точно исправил? 
А это что тогда?
https://github.com/ShindekiSan/Device/blob/3e9566660bc4b5ddba5b84c9e7aa84a9adbbfdf7/catalog.html#L129-L131

**Comment by ShindekiSan** [comment]
Исправил
